### ISSUE TITLE
Mejorar la búsqueda de recursos y colocar un mensaje de error si no se encuentran

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/visita-HCDN#2]
Actualmente la aplicación da problemas cuando no se encuentran los archivos de datos. Se abre la aplicación pero sin mostrar imágenes y parece fallada.

Lo ideal sería agregar un mensaje avisando al usuario que la aplicación inició correctamente, pero que necesita visitar el wiki para descargar el paquete de datos:

http://huayra.conectarigualdad.gob.ar/noticias/2015/05/18/ahora-con-huayra-podemos-visitar-el-congreso-de-la-naci%C3%B3n

PD: las instrucciones las podemos modificar más adelante, lo importante es que lleve al wiki, porque @hectorsanchez está consiguiendo el paquete de datos que tendríamos que agregar ahí.

**Comment by hugoruscitti** [comment]
Por cierto, cambiamos la URL a: http://huayra.conectarigualdad.gob.ar/visita-la-casa-del-pueblo en lugar de la página de noticias. Así nos queda igual de linda que las instrucciones de cdpedia como mencionaba en el issue #4

**Comment by iglosiggio** [comment]
Cerrado en 45fe443
