### ISSUE TITLE
Actualizar instrucciones del wiki para colocar nueva URL del paquete de datos

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/visita-HCDN#4]
Como mencionaba en el issue #3, si enviamos a los usuario que no tienen el paquete de datos a la página: http://huayra.conectarigualdad.gob.ar/noticias/2015/05/18/ahora-con-huayra-podemos-visitar-el-congreso-de-la-naci%C3%B3n

tendríamos que hacerles llegar el link de descarga de los datos, ¿modificamos la wiki con la url para descargar el zip o armamos una página de wiki nueva @iglosiggio  @hectorsanchez ?

**Comment by ftoledo** [comment]
Lo ideal seria que la aplicacion baje los datos desde internet. Es algo similar a lo que pensaba con cdpedia. Se instala la app, luego a abrirla y detectar que no esta "el paquete de datos" lo tiene que poder bajar directamente. Ya sea de nuestros servidores (mirror) o del original. 

Si no lo puede bajar es un error y deberiamos corregir el link de descarga. Eso nos obliga a mantener funcionando todo.
Saludos!

**Comment by hugoruscitti** [comment]
Concluimos que lo mejor sería subirlo a github releases en una primer versión, y ponernos en contacto con Matías Federici para consultarle por el soporte de la aplicación. Yo me encargo de esas dos cosas.

@iglosiggio vos podrías encargarte del mensaje de la aplicación si no encuentra el paquete de datos. La URL a la que hay que dirigir al usuario es http://huayra.conectarigualdad.gob.ar/visita-la-casa-del-pueblo

A grandes rasgos debería ser un mensaje muy similar al que tiene cdpedia:

![83538c18-a68a-45c2-9677-f83339b7f6d6](https://cloud.githubusercontent.com/assets/99183/18316047/8c5a9492-74ef-11e6-8f5d-b158fe2feac2.jpg)

Ah, por cierto, las instrucciones de cdpedia (que pueden servirnos de referencia) están acá: http://huayra.conectarigualdad.gob.ar/cdpedia

**Comment by hugoruscitti** [comment]
@digitalh, el texto para la página (http://huayra.conectarigualdad.gob.ar/visita-la-casa-del-pueblo) debería ser así:

```
La aplicación «Visitá la Casa del Pueblo», desarrollada en forma conjunta por la Cámara de Diputados de la Nación, el Ministerio de Educación de la Nación y Conectar Igualdad de Anses, permite iniciar un recorrido por la Cámara de Diputados y descubrir respuestas a las preguntas más frecuentes sobre el Poder Legislativo.

La aplicación require un conjunto de datos para funcionar de manera offline, que generalmente vienen instalados en la netbook del programa, pero que también se pueden descargar siguiendo alguno de estos pasos:

1. Bajar el archivo recursos.zip del siguiente link: https://github.com/HuayraLinux/visita-HCDN/releases/download/v0.5.21/recursos.zip
2. Copiá y descomprimir el archivo en la ruta /usr/share/visita-HCDN u otro directorio.
3. Luego volvé a iniciar la aplicación y pulsá el botón "ubicar datos" y seleccioná el directorio que hallas usando anteriormente para descomprimir los datos.
```

No hace falta que tenga imágenes ni nada, con ese texto va perfecto.

**Comment by hugoruscitti** [comment]
@iglosiggio el texto que debería mostrar la aplicación debería ser este:

```
La aplicación "Visitá la Casa del Pueblo" permite iniciar un recorrido por la Cámara de Diputados y descubrir respuestas a las preguntas más frecuentes sobre el Poder Legislativo.

Si ves este mensaje es porque la aplicación funciona, pero no encuentra los datos para funcionar de manera offline.

Te recomendamos seguir alguna de estas alternativas para conseguir los datos:

- Descargalos desde internet siguiendo estas instrucciones: http://huayra.conectarigualdad.gob.ar/visita-la-casa-del-pueblo
- Pedile al referente técnico de tu escuela que los cargue en tu netbook.
- Pedile a un compañero o profesor que te los pase en un pendrive.
```

Con el botón que tenga el texto "Ubicar datos" por supuesto.

**Comment by digitalh** [comment]
Van los textos: http://huayra.conectarigualdad.gob.ar/visita-la-casa-del-pueblo

**Comment by hugoruscitti** [comment]
https://github.com/nwjs/nw.js/issues/1162

**Comment by hugoruscitti** [comment]
Cerrando en:  https://github.com/HuayraLinux/visita-HCDN/commit/45fe443e987278d7c522a503b35a63e8d61c08b8
