### ISSUE TITLE
Generar una build para windows

### ISSUE THREAD

**Issue by iglosiggio** [HuayraLinux/visita-HCDN#5]
Armar la build para windows y ver que funcionen correctamente las soluciones a los issues de no encontrar los datos

**Comment by hugoruscitti** [comment]
Los binarios ya están en releases:

https://github.com/HuayraLinux/visita-HCDN/releases/tag/0.5.25

**Comment by hugoruscitti** [comment]
Testeado   👍 👍 👍

![msedge - win10_preview con shared folder running 2016-09-08 12-52-13](https://cloud.githubusercontent.com/assets/99183/18356453/15ad03be-75c3-11e6-84fd-a2102a6d1fd4.png)
