### ISSUE TITLE
No compila la aplicación en strider

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/visita-HCDN#6]
Parece un detalle menor, que unos módulos de node siguen estando en el archivo .install

http://ci.huayragnulinux.com.ar/huayralinux/visita-hcdn/

**Comment by iglosiggio** [comment]
A partir de f527e775a6de la build [anda](http://ci.huayragnulinux.com.ar/huayralinux/visita-hcdn/job/57d2d69d3615d50268276e9b)
