### ISSUE TITLE
Faltan las descripciones y metadata en el paquete

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/visita-HCDN#7]
![huayra con debsign running 2016-09-09 12-38-46](https://cloud.githubusercontent.com/assets/99183/18393044/603b119c-768a-11e6-856e-1616c9e16d97.png)

**Comment by iglosiggio** [comment]
Lo reparé en effcf86825f5adeb592cdd36bb5d90816b05e241, cierro
